### ISSUE TITLE
GetField on iOS causing `InvalidOperationException: No public parameterless constructor found` exception

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [JoshClose/CsvHelper#1073]
Hi. 

Any news on the iOS related problems CsvHelper has post version 2.0?

**Comment by JoshClose** [comment]
What problems are you referring to?

**Comment by JorgenEngenNapstad** [comment]
Oh sorry, the one with iOS not allowing expression trees as specified in #971 and #649. We just realized this wasn't working, which means we have to rewrite a ton of scripts for iOS. Is there any way of using the GetField and GetRecord methods now, or is "manually parsing" like below still the only option? 

```c#
var parser = new CsvParser( textReader );
while( true )
{
    var row = parser.Read();
    if( row == null )
    {
        break;
    }
}
```

**Comment by JoshClose** [comment]
You should be able to use `GetField` just fine on iOS I believe.

**Comment by JoshClose** [comment]
What line is that happening on?

Also, you should be able to do `GetField<DateTime>("fldStatusFromDate")` instead of parsing yourself.

**Comment by JorgenEngenNapstad** [comment]
This is the error message from xcode, which happens when using the script below
```
“InvalidOperationException: No public parameterless constructor found.
 at CsvHelper.ReflectionHelper.CreateInstanceDelegate (System.Type type, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
 at CsvHelper.ReflectionHelper.CreateInstanceWithoutContractResolver (System.Type type, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
 at CsvHelper.ObjectResolver.Resolve[T] (System.Object[] constructorArgs) [0x00000] in <00000000000000000000000000000000>:0
 at CsvHelper.Expressions.RecordManager..ctor (CsvHelper.CsvReader reader) [0x00000] in <00000000000000000000000000000000>:0
 at CsvHelper.CsvReader..ctor (CsvHelper.IParser parser) [0x00000] in <00000000000000000000000000000000>:0
 at Goontech.Syna.IO.Wells.WellInfoIoNpdCsvExploration.LoadWells (System.String source) [0x00000] in <00000000000000000000000000000000>:0
 at Goontech.Syna.Core.Wells.WellManager.LoadWells (System.String explorationWellsSource, System.String developmentWellsSource, System.String otherWellsSource) [0x00000] in <00000000000000000000000000000000>:0
 at Goontech.Syna.Pres.Managers.DataManager.ReadPublicData (Goontech.Syna.Pres.Managers.IDataReadOptions options) [0x00000] in <00000000000000000000000000000000>:0
 at Goontech.Syna.Startup.MainSceneInit.ReadData (Assets._Goontech.Scripts.Pres.Styling.ITheme theme, Goontech.Syna.Pres.ApplicationData.IUserSettings settings) [0x00000] in <00000000000000000000000000000000>:0
 at Goontech.Syna.Startup.MainSceneInit+<DoSteps>c__Iterator0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
 at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 

(Filename: currently not available on il2cpp Line: -1)
```

```c#
public IList<IWellInfo> LoadWells(string source)
{
	List<IWellInfo> wells = new List<IWellInfo>();

	StreamReader reader = File.OpenText(source);
	CsvReader csvReader = new CsvReader(reader);
	csvReader.Configuration.Delimiter = ",";
	csvReader.Configuration.TrimOptions = TrimOptions.Trim;

	NumberFormatInfo nfi = new NumberFormatInfo();
	nfi.NumberDecimalSeparator = ".";

	const string UNKNOWN_INT = "-999";
	const string UNKNOWN_STR_DOUBLE = "-999.25";

	try
	{
		csvReader.Read();
		csvReader.ReadHeader();

		while (csvReader.Read())
		{
			IWellInfo well = new WellInfo();

			well.WellboreName = csvReader.GetField<string>("wlbWellboreName");
			well.WellName = csvReader.GetField<string>("wlbWell");
			well.DrillingOperator= csvReader.GetField<string>("wlbDrillingOperator");
			well.ProductionLicense= csvReader.GetField<string>("wlbProductionLicence");
			well.Purpose = csvReader.GetField<string>("wlbPurpose");
			well.Status = csvReader.GetField<string>("wlbStatus");
			well.Content = csvReader.GetField<string>("wlbContent");
			well.WellType = csvReader.GetField<string>("wlbWellType");

			string strSubsea= csvReader.GetField<string>("wlbSubSea");
			well.IsSubsea= "YES".Equals(strSubsea);

			DateTime entryd = Conversions.ParseDate(csvReader.GetField<string>("wlbEntryDate"), "dd.mm.yyyy", DateTime.MaxValue);
			well.EntryDate = entryd.ToShortDateString();

			DateTime dt = Conversions.ParseDate(csvReader.GetField<string>("wlbCompletionDate"), "dd.mm.yyyy", DateTime.MaxValue);
			well.CompletionDate = dt.ToShortDateString();
			well.Field = csvReader.GetField<string>("wlbField");
			well.DrillingPermit = csvReader.GetField<string>("wlbDrillPermit");
			well.Discovery = csvReader.GetField<string>("wlbDiscovery");

			string discWellbore = csvReader.GetField<string>("wlbDiscoveryWellbore");
			well.IsDiscoveryWellbore = "YES".Equals(discWellbore);

			well.BottomHoleTemperature = Conversions.ParseDouble(csvReader.GetField<string>("wlbBottomHoleTemperature"));

			well.SeismicLocation = csvReader.GetField<string>("wlbSeismicLocation");

			well.MaxInclination = Conversions.ParseDouble(csvReader.GetField<string>("wlbMaxInclation")); ;
			well.KbElevation = Conversions.ParseDouble(csvReader.GetField<string>("wlbKellyBushElevation")); ;
			well.FinalVerticalDepth = Conversions.ParseDouble(csvReader.GetField<string>("wlbFinalVerticalDepth")); 
			well.TotalDepth = Conversions.ParseDouble(csvReader.GetField<string>("wlbTotalDepth"));
			well.WaterDepth = Conversions.ParseDouble(csvReader.GetField<string>("wlbWaterDepth"));
			well.KickOffPoint = Conversions.ParseDouble(csvReader.GetField<string>("wlbKickOffPoint"));

			well.AgeAtTd = csvReader.GetField<string>("wlbAgeAtTd");
			well.FormationAtTd = csvReader.GetField<string>("wlbFormationAtTd");
			well.MainArea = csvReader.GetField<string>("wlbMainArea");
			well.DrillingFacility = csvReader.GetField<string>("wlbDrillingFacility");
			well.TypeOfDrillingFacility = csvReader.GetField<string>("wlbFacilityTypeDrilling");

			string sIsMovable = csvReader.GetField<string>("wlbDrillingFacilityFixedOrMoveable");
			well.IsDrillingFacilityMovable = "MOVABLE".Equals(sIsMovable);

			string strMLT = csvReader.GetField<string>("wlbMultilateral");
			well.IsMultilateral = "YES".Equals(strMLT);

			well.EntryYear = Conversions.ParseInt(csvReader.GetField<string>("wlbEntryYear"));
			well.CompletionYear = Conversions.ParseInt(csvReader.GetField<string>("wlbCompletionYear"));

			well.PlotSymbol = Conversions.ParseInt(csvReader.GetField<string>("wlbPlotSymbol"));

			well.FormationAtHc1 = csvReader.GetField<string>("wlbFormationWithHc1");
			well.AgeOfFormationWithHc1 = csvReader.GetField<string>("wlbAgeWithHc1");
			well.FormationAtHc2 = csvReader.GetField<string>("wlbFormationWithHc2");
			well.AgeOfFormationWithHc2 = csvReader.GetField<string>("wlbAgeWithHc2");
			well.FormationAtHc3 = csvReader.GetField<string>("wlbFormationWithHc3");
			well.AgeOfFormationWithHc3 = csvReader.GetField<string>("wlbAgeWithHc3");              

			well.GeodeticDatum = csvReader.GetField<string>("wlbGeodeticDatum");

			well.Latitude = Conversions.ParseDouble(csvReader.GetField<string>("wlbNsDecDeg"));
			well.Longitude = Conversions.ParseDouble(csvReader.GetField<string>("wlbEwDesDeg"));
			well.UtmYNs= Conversions.ParseDouble(csvReader.GetField<string>("wlbNsUtm"));
			well.UtmXEw = Conversions.ParseDouble(csvReader.GetField<string>("wlbEwUtm"));
			well.UtmZone = Conversions.ParseInt(csvReader.GetField<string>("wlbUtmZone"));


			well.FactUrl = csvReader.GetField<string>("wlbFactPageUrl");
			well.MapUrl = csvReader.GetField<string>("wlbFactMapUrl");

			well.IdWellbore = Conversions.ParseInt(csvReader.GetField<string>("wlbNpdidWellbore"));

			well.Date_Uploaded = csvReader.GetField<string>("datesyncNPD");

			wells.Add(well);
		}
	}
	catch (MissingFieldException mfe)
	{
		//Console.WriteLine(mfe.Message);
	}

	return wells;          
}
```

**Comment by JoshClose** [comment]
If you're only using `GetField`, this shouldn't happen.

The constructor for `CsvReader` creates a new instance of `RecordManager` which uses the `ObjectResolver`. The `ObjectResolver` can't be used on iOS. I can probably lazy load the creation of those since they won't be used in a `GetField` only scenario.

**Comment by JoshClose** [comment]
I just released version `8.0.0-alpha01`. Can you give that a try? You'll need to enable pre-releases to see it.

**Comment by JorgenEngenNapstad** [comment]
@JoshClose It worked. Thank you for the quick response and fix!

**Comment by JoshClose** [comment]
Awesome! I wanted to get some more breaking changes in before I released 8.0... but it's looking like I'm not going to have much time in the near future, so I may just release it sooner than later.

**Comment by JoshClose** [comment]
I'm going to close this. It will be out in 8.0, but you can use it in the pre-releases for now.

**Comment by githubbar** [comment]
I'm building Unity3D  app. I'm still getting "InvalidOperationException: No public parameterless constructor found" when calling  GetRecords. 

I'm only getting this when compiling to WebGL. Works fine under Unity editor. Any solution for this?
