### ISSUE TITLE
Map columns to constructor parameters

### ISSUE THREAD

**Issue by kyberias** [JoshClose/CsvHelper#634]
I have a class that doesn't have writable properties but instead has a constructor.

Can I just somehow give a function to the mapper that it should use to map a row to object instead of specifying individual fields?

**Comment by jamesbascle** [comment]
Yes!  Use the ConstructUsing method with your custom lambda in the constructor of your CsvClassMap subclass.

**Comment by kyberias** [comment]
```
class Person
{
   public Person(string name, string address)
   {
      // ...
   }
}

class PersonMap : CsvClassMap<Person>
    {
        public PersonMap()
        {
             // how do I construct a Person based on row here?
        }
    }

```

**Comment by JoshClose** [comment]
Do the properties have a private setter? If so, you can do this.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Name,Address");
		writer.WriteLine("first,123 4th st");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.IncludePrivateProperties = true;
		csv.Configuration.RegisterClassMap<PersonMap>();
		csv.GetRecords<Person>().ToList().Dump();
	}
}

public class Person
{
	public string Name { get; private set; }
	public string Address { get; private set; }
	
	public Person(string name, string address)
	{		
		Name = name;
		Address = address;
	}
}

public sealed class PersonMap : CsvClassMap<Person>
{
	public PersonMap()
	{		
		ConstructUsing(() => new Person(null, null));
		Map(m => m.Name);
		Map(m => m.Address);
	}
}
```

**Comment by MarkPThomas** [comment]
Using v. 3.1.1, with the appropriate naming changes (e.g. `CsvClassMap` changed to `ClassMap`), I get a thrown exception doing this. I am attempting a nearly perfectly analogous situation.

The exception states: {"The property 'System.String RegionName' has no 'set' accessor"}

I am making sure to use `csv.Configuration.IncludePrivateMembers = true;` as I figured that might be the trick to getting access to the `private set;` of the property...

**Comment by kyberias** [comment]
I don't understand what is the purpose of ContructUsing with constructor if you have to have private or public properties. My original need was to have a method of constructing the object by hand without mapper getting in the way.

**Comment by JoshClose** [comment]
@MarkPThomas Does this work for you? http://joshclose.github.io/CsvHelper/examples#private-members

**Comment by JoshClose** [comment]
@kyberias I don't understand. You want to have an object automatically read in without a mapping?

**Comment by MarkPThomas** [comment]
@JoshClose , perfect! That works for me.

FYI, the direct link does not work. You can still access that page by navigating to [http://joshclose.github.io/CsvHelper/](http://joshclose.github.io/CsvHelper/) and then selecting the option from the menu strip.

**Comment by JoshClose** [comment]
The sub page links/refresh issue is fixed.

**Comment by kyberias** [comment]
@JoshClose, I still don't understand whether CsvHelper can construct my object by injecting the contructor parameters **only**. Why does it need private setters? Or does it?

The example here is **really** confusing:

http://joshclose.github.io/CsvHelper/examples/#private-members

**Comment by JoshClose** [comment]
It doesn't need private setters. That example is just showing that you can use constructor parameters if you have private setters.

There is a config option [ShouldUseConstructorParameters](http://joshclose.github.io/CsvHelper/configuration/#shoulduseconstructorparameters). You can just set that to true if you want it to always use constructor parameters.

The docs aren't complete. Hopefully once they get filled in more, things like this will be less confusing.

**Comment by gojanpaolo** [comment]
I tried settings `ShouldUseConstructorParameters = true` but then I get a `CsvHelper.ReaderException: 'No members are mapped for type 'ConsoleApp1.DrgRecord'.'`

```
public class DrgRecord
{
	public DrgRecord(DateTime date, TimeSpan time)
	{
		Date = date;
		Time = time;
	}

	public DateTime Date { get; }
	public TimeSpan Time { get; }
	public DateTime DateTime => Date.Add(Time);
}

public class DrgRecordCsvClassMap : ClassMap<DrgRecord>
{
	public DrgRecordCsvClassMap()
	{
		Map(r => r.Time).Index(0).Name("[Time 24hr hh:mm:ss] ");
		Map(r => r.Date).Index(1).Name(" [Date dd/mm/yy 27/1/98] ").TypeConverterOption.Format("dd/MM/yy");
	}
}

//... usage
var config = new Configuration
{
	ShouldUseConstructorParameters = type => true
};

config.RegisterClassMap<DrgRecordCsvClassMap>();
```

**Comment by JoshClose** [comment]
Currently you can't use a mapping with constructor parameters. There is a feature request for this. #955
